name: Test Pipeline2
on: push
 
 
jobs:
  job1:
    runs-on: ubuntu-latest
 
    steps:
    - name: Step1
      run: echo "Step1 executed"
 
    - name: Stpe2
      run: echo "Step2 Executed"

    - name: checkout the code
      uses: actions/checkout@v6.0.1

    - name: Read the content of code repo
      run: cat 3.txt
